version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - shop

  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    command:
      - postgres
      - -c
      - wal_level=logical
      - -c
      - max_prepared_transactions=10
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - shop

  jaeger:
    image: jaegertracing/all-in-one:1.57
    container_name: jaeger
    restart: unless-stopped
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "14268:14268"
    networks:
      - shop

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    restart: unless-stopped
    command:
      - "--config=/etc/otelcol-contrib/config.yaml"
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "4319:4317"
      - "4320:4318"
      - "8889:8889"
    depends_on:
      - jaeger
    networks:
      - shop

  identity-service:
    build:
      context: ../../
      dockerfile: internal/services/identity_service/Dockerfile
    container_name: identity-service
    ports:
      - "5002:5002"
      - "6602:6600"
    environment:
      - APP_ENV=docker
    depends_on:
      - postgres
      - rabbitmq
      - otel-collector
    networks:
      - shop

  product-service:
    build:
      context: ../../
      dockerfile: internal/services/product_service/Dockerfile
    container_name: product-service
    ports:
      - "5000:5000"
      - "6601:6600"
    environment:
      - APP_ENV=docker
    depends_on:
      - postgres
      - rabbitmq
      - otel-collector
    networks:
      - shop

  inventory-service:
    build:
      context: ../../
      dockerfile: internal/services/inventory_service/Dockerfile
    container_name: inventory-service
    ports:
      - "5004:5004"
    environment:
      - APP_ENV=docker
    depends_on:
      - postgres
      - rabbitmq
      - otel-collector
    networks:
      - shop

networks:
  shop:

volumes:
  pgdata:
