services:

  identity-service:
    build:
      context: ../..
      dockerfile: internal/services/identity_service/Dockerfile
    container_name: identity-service
    ports:
      - "5002:5002"
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      # JWT disabled temporarily for observability and MTTR experiments
      DISABLE_AUTH: "true"
    depends_on:
      - postgres
      - rabbitmq
      - otel-collector
    networks:
      - shop

  inventory-service:
    build:
      context: ../..
      dockerfile: internal/services/inventory_service/Dockerfile
    container_name: inventory-service
    ports:
      - "5004:5004"
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      # JWT disabled temporarily for observability and MTTR experiments
      DISABLE_AUTH: "true"
    depends_on:
      - postgres
      - rabbitmq
      - otel-collector
    networks:
      - shop

  product-service:
    build:
      context: ../..
      dockerfile: internal/services/product_service/Dockerfile
    container_name: product-service
    ports:
      - "5000:5000"
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      # JWT disabled temporarily for observability and MTTR experiments
      DISABLE_AUTH: "true"
      # Debug endpoints for incident simulation (HTTP 500, latency, panic, db-timeout)
      ENABLE_DEBUG: "true"
    depends_on:
      - postgres
      - rabbitmq
      - otel-collector
    networks:
      - shop

networks:
  shop:
    name: docker-compose_shop
    external: true
